export const questions = [
  ["Tomorrow, I plan to", "study"],
  ["After work, I want to", "exercise"],
  ["On weekends, I usually", "shop"],
  ["For breakfast, I often", "eat"],
  ["When I'm bored, I like to", "draw"],
  ["During vacations, I love to", "travel"],
  ["At night, I usually", "read"],
  ["In the gym, I prefer to", "exercise"],
  ["On special occasions, I", "celebrate"],
  ["After school, I want to", "play"],
  ["On holidays, I visit", "family"],
  ["For dessert, I like to", "bake"],
  ["During winter, I enjoy", "skiing"],
  ["In the park, I often", "jog"],
  ["When I need to unwind, I", "meditate"],
  ["In my free time, I", "paint"],
  ["Every morning, I", "stretch"],
  ["In the afternoon, I", "rest"],
  ["Before bed, I", "journal"],
  ["On weekends, I like to", "clean"],
  ["For my birthday, I", "party"],
  ["Every evening, I", "cook dinner"],
  ["In summer, I", "swim"],
  ["During fall, I", "hike"],
  ["On road trips, I", "sing"],
  ["For fun, I often", "dance"],
  ["In my spare time, I", "write"],
  ["During breaks, I", "relax"],
  ["On rainy days, I", "watch movies"],
  ["When it’s hot, I drink", "water"],
  ["For my hobbies, I", "knit"],
  ["On my birthday, I", "celebrate"],
  ["Before a test, I", "study"],
  ["During the weekend, I", "read"],
  ["For my lunch break, I", "eat"],
  ["Every summer, I", "travel"],
  ["When it’s cold, I", "wear jackets"],
  ["Before a trip, I", "pack"],
  ["For relaxation, I", "meditate"],
  ["During the night, I", "sleep"],
  ["On Sundays, I", "rest"],
  ["Before starting my day, I drink", "coffee"],
  ["For dinner, I", "cook"],
  ["During my lunch break, I", "read"],
  ["When I’m at the beach, I", "swim"],
  ["In the office, I", "work"],
  ["For fun, I", "play games"],
  ["When I'm stressed, I", "sleep"],
  ["On holidays, I buy", " presents"],
  ["For entertainment, I watch", " TV"],
];

export function toString(arr: Array<string>) {
  return arr.join(" ");
}
